// <auto-generated />
using System;
using CateringApp.Services.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CateringApp.Migrations
{
    [DbContext(typeof(CateringDbContext))]
    [Migration("20260828180725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CateringApp.Models.Entity.DetailPesanan", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("Catatan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("catatan");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("HargaSatuan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("harga_satuan");

                    b.Property<int>("Jumlah")
                        .HasColumnType("int")
                        .HasColumnName("jumlah");

                    b.Property<int>("PaketId")
                        .HasColumnType("int")
                        .HasColumnName("paket_id");

                    b.Property<int>("PesananId")
                        .HasColumnType("int")
                        .HasColumnName("pesanan_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("DetailId");

                    b.HasIndex("PaketId");

                    b.HasIndex("PesananId");

                    b.ToTable("detail_pesanan");
                });

            modelBuilder.Entity("CateringApp.Models.Entity.KategoriMenu", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("kategori_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deskripsi");

                    b.Property<string>("NamaKategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_kategori");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("KategoriId");

                    b.ToTable("kategori_menu");
                });

            modelBuilder.Entity("CateringApp.Models.Entity.PaketMenu", b =>
                {
                    b.Property<int>("PaketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paket_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaketId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeskripsiMenu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deskripsi_menu");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("harga");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int")
                        .HasColumnName("kategori_id");

                    b.Property<string>("NamaPaket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_paket");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PaketId");

                    b.HasIndex("KategoriId");

                    b.ToTable("paket_menu");
                });

            modelBuilder.Entity("CateringApp.Models.Entity.Pembayaran", b =>
                {
                    b.Property<int>("PembayaranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pembayaran_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PembayaranId"));

                    b.Property<string>("BuktiTransfer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bukti_transfer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("JumlahBayar")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("jumlah_bayar");

                    b.Property<string>("MetodePembayaran")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metode_pembayaran");

                    b.Property<int>("PesananId")
                        .HasColumnType("int")
                        .HasColumnName("pesanan_id");

                    b.Property<string>("StatusVerifikasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status_verifikasi");

                    b.Property<DateTime>("TanggalBayar")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_bayar");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PembayaranId");

                    b.HasIndex("PesananId")
                        .IsUnique();

                    b.ToTable("pembayaran");
                });

            modelBuilder.Entity("CateringApp.Models.Entity.Pengguna", b =>
                {
                    b.Property<int>("PenggunaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pengguna_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PenggunaId"));

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alamat");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_lengkap");

                    b.Property<string>("NomorTelepon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nomor_telepon");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<int>("PeranId")
                        .HasColumnType("int")
                        .HasColumnName("peran_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("PenggunaId");

                    b.HasIndex("PeranId");

                    b.ToTable("pengguna");
                });

            modelBuilder.Entity("CateringApp.Models.Entity.Peran", b =>
                {
                    b.Property<int>("PeranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("peran_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeranId"));

                    b.Property<string>("NamaPeran")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_peran");

                    b.HasKey("PeranId");

                    b.ToTable("peran");
                });

            modelBuilder.Entity("CateringApp.Models.Entity.Pesanan", b =>
                {
                    b.Property<int>("PesananId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pesanan_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PesananId"));

                    b.Property<string>("AlamatPengiriman")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alamat_pengiriman");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("NomorPesanan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nomor_pesanan");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int")
                        .HasColumnName("pengguna_id");

                    b.Property<string>("StatusPesanan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status_pesanan");

                    b.Property<DateTime>("TanggalPengiriman")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_pengiriman");

                    b.Property<DateTime>("TanggalPesan")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_pesan");

                    b.Property<decimal>("TotalBayar")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_bayar");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PesananId");

                    b.HasIndex("PenggunaId");

                    b.ToTable("pesanan");
                });

            modelBuilder.Entity("CateringApp.Models.Entity.DetailPesanan", b =>
                {
                    b.HasOne("CateringApp.Models.Entity.PaketMenu", "Paket")
                        .WithMany()
                        .HasForeignKey("PaketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CateringApp.Models.Entity.Pesanan", "Pesanan")
                        .WithMany("DetailPesanans")
                        .HasForeignKey("PesananId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paket");

                    b.Navigation("Pesanan");
                });

            modelBuilder.Entity("CateringApp.Models.Entity.PaketMenu", b =>
                {
                    b.HasOne("CateringApp.Models.Entity.KategoriMenu", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("CateringApp.Models.Entity.Pembayaran", b =>
                {
                    b.HasOne("CateringApp.Models.Entity.Pesanan", "Pesanan")
                        .WithOne("Pembayaran")
                        .HasForeignKey("CateringApp.Models.Entity.Pembayaran", "PesananId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pesanan");
                });

            modelBuilder.Entity("CateringApp.Models.Entity.Pengguna", b =>
                {
                    b.HasOne("CateringApp.Models.Entity.Peran", "Peran")
                        .WithMany()
                        .HasForeignKey("PeranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peran");
                });

            modelBuilder.Entity("CateringApp.Models.Entity.Pesanan", b =>
                {
                    b.HasOne("CateringApp.Models.Entity.Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("CateringApp.Models.Entity.Pesanan", b =>
                {
                    b.Navigation("DetailPesanans");

                    b.Navigation("Pembayaran");
                });
#pragma warning restore 612, 618
        }
    }
}
